kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: alpine
  commands:
  - pwd
  - rm -vfr docs/*
  - ls
  - chmod +x ./hugo
  - ./hugo
  - ls
  - ls -l docs