kind: pipeline
name: default

steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.55
    validate: true

- name: deploy
  image: appleboy/drone-scp
  settings:
    host: 94.191.32.237
    target: /data
    source: docs/*
    username:
      from_secret: root
    password:
      from_secret: Admin568128361
    port:
      from_secret: 22
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
